language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t kartikmishra29/docker-react -f Dockerfile.dev .
script:
    - docker run -e CI=true kartikmishra29/docker-react npm run test
